@startuml
skinparam shadowing false
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
    FontName Arial
}
skinparam linetype ortho

abstract class Media {
  - id: int
  - title: String
  - category: String
  - cost: float
  + getId(): int
  + setId(int id): void
  + getTitle(): String
  + setTitle(String title): void
  + getCategory(): String
  + setCategory(String category): void
  + getCost(): float
  + setCost(float cost): void
  + equals(Object obj): boolean
  + compareTo(Media other): int
}

class Disc extends Media {
  - length: int
  - director: String
  + getLength(): int
  + getDirector(): String
}

interface Playable {
  + play(): void throws PlayerException
}

class DigitalVideoDisc extends Disc implements Playable {
  + play(): void throws PlayerException
  + toString(): String
}

class CompactDisc extends Disc implements Playable {
  - artist: String
  - tracks: ArrayList<Track>
  + getArtist(): String
  + addTrack(Track track): void
  + removeTrack(Track track): void
  + getLength(): int
  + play(): void throws PlayerException
  + toString(): String
}

class Track implements Playable {
  - title: String
  - length: int
  + getTitle(): String
  + getLength(): int
  + play(): void throws PlayerException
}

class Book extends Media {
  - authors: List<String>
  + addAuthor(String authorName): void
  + removeAuthor(String authorName): void
  + toString(): String
}

class Cart {
  + MAX_NUMBERS_ORDERED: int = 20
  - itemsOrdered: ObservableList<Media>
  + addMedia(Media media): void throws LimitExceededException
  + removeMedia(Media media): void
  + totalCost(): float
  + getItemsOrdered(): ObservableList<Media>
}

class Store {
  - itemsInStore: ArrayList<Media>
  + addMedia(Media media): void
  + removeMedia(Media media): void
  + getItemsInStore(): ArrayList<Media>
}

class PlayerException extends java.lang.Exception {
}

class LimitExceededException extends java.lang.Exception {
}

Store o-up- Media : contains >
Cart o-down- Media : contains >
CompactDisc "1" *-- "*" Track : contains >

@enduml
