@startuml
left to right direction
actor "Customer" as C
actor "Store Manager" as M

package AIMS {
  usecase "View Store" as UC1
  usecase "View Cart" as UC2
  usecase "Add Media to Cart" as UC3
  usecase "Remove Media from Cart" as UC4
  usecase "Play Media (DVD/Track/CD)" as UC5
  usecase "Place Order" as UC6
  usecase "Filter Media in Cart" as UC7
  usecase "Add Media to Store" as UC8
  usecase "Remove Media from Store" as UC9
}

C --> UC1
C --> UC2
C --> UC3
C --> UC4
C --> UC5
C --> UC6
C --> UC7

M --> UC8
M --> UC9

UC1 .> UC3 : extends
UC1 .> UC5 : extends
UC2 .> UC4 : extends
UC2 .> UC5 : extends
UC2 .> UC6 : extends
UC2 .> UC7 : extends

@enduml
